backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "content"
    label: "Контент сайта"
    files:
      - file: "data.json"
        label: "Главная страница"
        name: "index"
        fields:
          - {label: "Заголовок", name: "hero_title", widget: "string"}
          - {label: "Телефон для связи", name: "phone", widget: "string"}
          - {label: "Рекламное фото", name: "promo_img", widget: "image"}
          - {label: "Услуги (через запятую)", name: "services", widget: "list"}
          
